### ISSUE TITLE
Yaml oneToMany relationships are reversed

### ISSUE THREAD

**Issue by eamondaly** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#103]
Not sure when it changed, but I think the Yaml 2 writer for oneToMany relationships is now reversed (and broken). Running against Sakila (http://dev.mysql.com/doc/index-other.html) I get this relationship for Country to City:

``` YAML
Entities\Country:
    type: entity
    table: sakila.country
    repositoryClass: Repositories\CountryRepository
    id:
        id:
            type: smallint
            unsigned: true
            generator:
                strategy: AUTO
    fields:
        country:
            type: string
            length: 50
        last_update:
            type: timestamp
            default: CURRENT_TIMESTAMP
    manyToOne:
        city:
            targetEntity: City
            inversedBy: countries
            joinColumn:
                name: id
                referencedColumnName: country_id
                onDelete: ~
                nullable: false
```

However, with Anno I get the expected results:

``` PHP
    /**
     * @ORM\OneToMany(targetEntity="City", mappedBy="country")
     * @ORM\JoinColumn(name="country_id", referencedColumnName="id", nullable=false)
     */
    protected $cities;
```
