### ISSUE TITLE
[dc2] Possibility to specify a repositoryClass

### ISSUE THREAD

**Issue by Domisys** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#17]
It would be nice to be able to automatically add the repositoryClass for Doctrine2 (http://www.doctrine-project.org/docs/orm/2.0/en/reference/annotations-reference.html#entity)

``` yml
\Entity\Foobar:
    type: Entity
    repositoryClass: FoobarRepository
    ....
```

``` php
<?php
/**
 * @Entity(repositoryClass="Entity\FoobarRepository")
 */
class Foobar {
}
```

I'd add a parameter like 'useAutomaticRepository' that'll add 'Repository' to the entity name.
