### ISSUE TITLE
My relations and indexes are duplicated

### ISSUE THREAD

**Issue by yoh** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#2]
Hello and thanks for your work.
I am an user of mysql-workbench-doctrine-plugin and I try this new project (mysql-workbench-schema-exporter).

I use MySQLWorkbench 5.1.18 and 5.2.27. 
I would like generate YAML for Doctrine 1.

The probleme is that all my relations and indexes are duplicated in the generated YAML :

```
Prestation:
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
    contrat_id:
      type: integer(4)
      notnull: true
    produit_id:
      type: integer(4)
  relations:
    Contrat:
      class: Contrat
      local: contrat_id
      foreign: id
      foreignAlias: Prestations
      onDelete: no action
      onUpdate: no action
    Produit:
      class: Produit
      local: produit_id
      foreign: id
      foreignAlias: Prestations
      onDelete: no action
      onUpdate: no action
    Contrat:
      class: Contrat
      local: contrat_id
      foreign: id
      foreignAlias: Prestations
      onDelete: no action
      onUpdate: no action
    Produit:
      class: Produit
      local: produit_id
      foreign: id
      foreignAlias: Prestations
      onDelete: no action
      onUpdate: no action
  indexes:
    fk_prestation_contrat:
      fields: [contrat_id]
      type: foreign
    fk_prestation_produit:
      fields: [produit_id]
      type: foreign
    fk_prestation_contrat:
      fields: [contrat_id]
      type: foreign
    fk_prestation_produit:
      fields: [produit_id]
      type: foreign
  options:
    charset: utf8
    type: InnoDB
```

Do you think my .mwb is faulty ?
(Sorry for my bad english)
