### ISSUE TITLE
[dc2][yml] Primary keys and fields

### ISSUE THREAD

**Issue by Domisys** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#20]
In doctrine2 yml mapping, primary keys should be in the 'id' definition, and the other columns should be in the 'fields' definition (columns ATM, like in dc1)

http://www.doctrine-project.org/docs/orm/2.0/en/reference/yaml-mapping.html#example

``` yml
\Entity\Foobar:
    type: Entity
    id:   # the main defintion
        id: # the actual field name
            type: integer
            generator:
                strategy: AUTO
    fields:  # was columns
        name: # a field/column
            type: string
            length: 50

```
