### ISSUE TITLE
[dc2] Possibility to specify the repository namespace

### ISSUE THREAD

**Issue by Domisys** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#21]
It would be nice to specify the repository namespace (once #17 is done).

It would be a parameter like 'useRepositoryNamespace' => '\My\Namespace\Repository',

This parameter sould be prepended to the generated repository name.

``` yml
\My\Namespace\Entity\Foobar:
    type: Entity
    repositoryClass: \My\Namespace\Repository\FoobarRepository
    ...
```

http://www.doctrine-project.org/docs/orm/2.0/en/reference/annotations-reference.html#annref-entity

``` php
<?php
/**
 * @Entity(repositoryClass="\My\Namespace\Repository\FoobarRepository")
 */
class Foobar {
}
```
