### ISSUE TITLE
Externals relations not supported on Doctrine1 schema ?

### ISSUE THREAD

**Issue by jtexier** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#26]
Hi,

I recently migrate from LUA lib to PHP one.
On a Doctrine 1 schema, external relations such as :

```
{doctrine:externalRelations}
    GuardUser:
      class: sfGuardUser
      local: user_id
      foreign: id
      foreignAlias: Profile
      foreignType: one
      onDelete: cascade
{/doctrine:externalRelations}
```

is not handled at all by PHP library where it was working perfectly with LUA thing.
Am I missing something ?

Regards
