### ISSUE TITLE
integer(20) becomes integer(8)

### ISSUE THREAD

**Issue by basz** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#4]
jep for id fields that is...

As I defined in YAML an PK field 

```
    id:
        primary:        true
        autoincrement:  true
        type:           integer(20)
```

load this into through doctrine into the PHP objects, and then into a mysql database, reversed enginered with workbench, and finally exported to yaml...

note the difference... in mysql an BIGINT(20) becomes integer(8)

```
id:
  type: integer(8)
  primary: true
  notnull: true
  autoincrement: true
```
