### ISSUE TITLE
Decimal bug when exporting to YAML

### ISSUE THREAD

**Issue by Pym** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#49]
Hi there,

I'm using [the latest version](https://github.com/johmue/mysql-workbench-schema-exporter/tree/9fa543e7c7ca9dce526f58c8bc3c8bbdc05d501f) of mysql-workbench-schema-exporter (as I open this issue) with MySQL Workbench 5.2.37.

I encounter a problem with the Doctrine 1 formatter.

The decimal data type is not rendered as expected. The scale should be present in the YAML and the precision and the scale are reversed :

```
original_output:
  price:
    type: decimal(2,5) # wrong order
    notnull: true

must_be:
  price:
    type: decimal(5)
    scale: 2
    notnull: true
```

Please see this page for more information:
http://www.doctrine-project.org/documentation/manual/1_2/en/defining-models:columns:data-types:decimal
