### ISSUE TITLE
1:n local - foreign reversed in generated schema

### ISSUE THREAD

**Issue by danyi-david** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#62]
Hi

I've ran into this problem while generating the schema from my database. I first thought its a problem on my part, but it appears its the same with the included sakila.mwb so I'll be refering to that as a test case.

The id and local_id parts are mixed up in the relation definition of the schema. If you take a look at the City - Country relation defined in 'City' the local: should be country_id and foreign: should be id (also its foreignAlias: City), as the relation is defined from the point of view of the actual model where its defined in(as seen in http://readthedocs.org/docs/doctrine/en/latest/en/manual/yaml-schema-files.html#verbose-syntax ), so the correct syntax there would be:

``` yaml
Entity\City:                                                                                                                                                                                                                                                                  
  type: Entity
...
  relations:
    Countries: --(instead of Country )
      class: Country
      local: country_id
      foreign: id
      foreignAlias: Cities
      onDelete: restrict
      onUpdate: cascade
```

I only have experience with doctrine yaml schemas, not annotations so can't tell if its good there, but its the same error with both doctrine1 and doctrine2 yaml.
